[package]
name = "menhue"
version = "0.1.0"
edition = "2021"

[dependencies]
block2 = "0.5.1"
objc2 = "0.5.2"
objc2-foundation = { version = "0.2.2", features = ["all"] }
objc2-app-kit = { version = "0.2.2", features = ["all"] }
